### ISSUE TITLE
询问训练的数据量以及训练配置及时间

### ISSUE THREAD

**Issue by wlll123456** [Liac-li/MM-self-improve-qwen2vl#2]
大佬，您好。我想询问训练的数据量大小以及训练配置及训练时间

**Comment by Liac-li** [comment]
你好，训练的数据量就是 geoqa 的训练集 3000 条。训练默认用 3 个 epoch3。

我们的方法用的是自训练，所以最后对于一个 n 条训练集，大概会有 n 条 cot 数据，n 条 self-refine 数据加上 2n 条 self-select 数据

对于 self-select scaling 部分，我们会采样很多条 self-select 数据获得具有不同数量样本的self-select，比如从包含 2 到 6 个模型预测的self-select 样本一般会获得大约 3 万条数据


比较细节的训练设置可以参考我们的论文，Vision-Language Models Can Self-Improve Reasoning via Reflection 的说明，或者看qwen2vl_lora_sft_geoqa.yaml 这个里面的设置

**Comment by wlll123456** [comment]
谢谢大佬解答
