### ISSUE TITLE
希望完善下readme

### ISSUE THREAD

**Issue by thunder95** [Liac-li/MM-self-improve-qwen2vl#4]
非常棒的工作分享，感谢。

merge_data.py部分应该怎么运行，
可以给个示例命令吗
里面涉及到outputs/....add.json从哪里来

辛苦大佬能给下完整的复现尝试过程。

**Comment by thunder95** [comment]
主要是执行的步骤顺序不太清楚。
应该是要先运行add info, 但是Qwen2-geoqa_iter4gen_scale10_test_10_select0.json这种文件又怎么生成的？

**Comment by thunder95** [comment]
若是eval创建的，那么又需要lora权重，但是又回到训练那一步，训练有需要先产生数据。

**Comment by Liac-li** [comment]
理论上来讲，直接根据一键运行脚本 run.py 就可以完成论文的复现了，默认是跑 3 轮 iter
README 我之后会再完善一下。可能提供一个更细节内容到 docs/details.md 里，可能就不放主 README 里了

所有脚本的调用顺序其实都在 run.py (self-improve), self_select_scaling.py(self-select scaling) 中了，可以参考。其中默认的，self-improve 会跑 3 轮迭代，self-select scaling 在第三轮的基础上做 self-select 的 scaling up

#### Q1: merge_data.py部分应该怎么运行

  merge_data 逻辑是利用将已经检查过结果的文件组合成下一轮训练的数据。
  比如模型预测出了 test_sample.json, 应该需要先用 data_process/geoqa/add_test_info.py 添加后续判断正误需要的 m3cot_choice, 和对应的 m3cot_answers 这两个信息，就到 merge_data 中了。
  merge_data 会进行判断模型infer结果的正误，然后就将当前 iter 的 sft，refine， select 存到 data/geoqa 里。然后 data 里面会有一个脚本去组合一下构建成 Llama-factory 需要的 sharegpt 形式的训练数据
  构建训练集我们组合已有的所有数据，比如从 iter2 训练 iter3 的时候，会组合 iter0， iter1， iter2 的数据，而做测试的时候，只需要组合 iter2 的测试集的采样

#### Q2: Qwen2-geoqa_iter4gen_scale10_test_10_select0.json这种文件又怎么生成的？

这个其实是后续做 self-select scaling 的部分，也就是将采样用 3 开到了 10，这个是 iter4，也就是说是通过原有的每轮采样 3 次的self-improve 过程跑了3轮得到一个 iter3 的lora ckpt，基于这个之上做了 10 次采样训练了新的模型，然后做了 10 次 test 采样来观察我们的 self-select 是否能在采样 n 上 scaling

**Comment by thunder95** [comment]
@Liac-li 非常感谢耐心回复，我再仔细研究下源码。
